public with sharing class carSearchResultController {
   @AuraEnabled(cacheable=true)
   public static List<Car__c> getCars(String carTypeId){
   if(String.isEmpty(carTypeId)){
    return [Select Id, Name,Picture__c, Contact__r.Name, 
    Geolocation__latitude__s,Geolocation__longitude__s From Car__c
    where Available_For_Rent__c = true ];
   }
   else {
    return [Select Id, Name,Picture__c, Contact__r.Name, 
    Geolocation__latitude__s,Geolocation__longitude__s From Car__c
    where Available_For_Rent__c = true
    AND Car_type__c =: carTypeId ];
    
   }
   }
}